### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ghp-import': 'ghp-import'

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/elsa#89]
Builds of python.cz and pyvec.org started to consistently fail with the same error:

```
fatal: ambiguous argument 'refs/remotes/origin/gh-pages': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Rewriting gh-pages branch...
Traceback (most recent call last):
  File "runserver.py", line 7, in <module>
    cli(app, freezer=freezer, base_url='https://python.cz')
  File "/home/runner/.local/share/virtualenvs/python.cz-imsbSAMP/lib/python3.7/site-packages/elsa/_cli.py", line 174, in cli
    return command()
  File "/home/runner/.local/share/virtualenvs/python.cz-imsbSAMP/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/.local/share/virtualenvs/python.cz-imsbSAMP/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/runner/.local/share/virtualenvs/python.cz-imsbSAMP/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/runner/.local/share/virtualenvs/python.cz-imsbSAMP/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/.local/share/virtualenvs/python.cz-imsbSAMP/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/.local/share/virtualenvs/python.cz-imsbSAMP/lib/python3.7/site-packages/elsa/_cli.py", line 171, in deploy
    deploy_(path, remote=remote, push=push, show_err=show_git_push_stderr)
  File "/home/runner/.local/share/virtualenvs/python.cz-imsbSAMP/lib/python3.7/site-packages/elsa/_deployment.py", line 73, in deploy
    html_dir
  File "/home/runner/.local/share/virtualenvs/python.cz-imsbSAMP/lib/python3.7/site-packages/elsa/_deployment.py", line 23, in run
    return subprocess.run(cmd, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ghp-import': 'ghp-import'
```

See https://github.com/pyvec/python.cz/actions or https://github.com/pyvec/pyvec.org/actions. I think I need help with debugging this. I feel like the first lines about `ambiguous argument` are not relevant, but then Elsa cannot find `ghp-import`. I do update dependencies on the projects, but I don't recall anything relevant to ghp-import. Even if, Elsa should probably update to work with the newest deps? The projects have the same setup for months, this has only started on python.cz a few days ago, not after merging a new dependency, but during the nightly build. Maybe GitHub has changed something?

**Comment by hroncok** [comment]
https://github.com/pyvec/python.cz/actions

 - latest success before the problem: Successfully installed  ... pipenv-2021.5.29
 - first failure: Successfully installed ... pipenv-2021.11.5.post0

That version was yanked from pipy.

 - now the build seem fixed again with: Successfully ... pipenv-2021.5.29

However, pipenv  2021.11.9  got out 6 hours ago and it might break this again.

**Comment by hroncok** [comment]
My interpretation of the problem is that that yanked pipenv version did not install all dependencies.

**Comment by hroncok** [comment]
pipenv-2021.11.9 works

**Comment by honzajavorek** [comment]
Wow, thanks! ❤️ 🙌 So basically it happened because we don't have a pipenv version pinned in the CI and upgraded only with e.g. dependabot? 🤔 Not that I'd like to pin it, I think this happens quite rarely and the benefit of always grabbing the latest one overweights the downsides on community projects like these.

**Comment by hroncok** [comment]
Yes. And because pipenv released a completely broken version :/

**Comment by honzajavorek** [comment]
I use poetry on junior.guru and I'm really satisfied with it. But I'm not eager to spend all our python sprints just migrating our projects from old broken tech to shiny new tech :( Like travis to github.
